ALTER TABLE transaction_histories
    MODIFY COLUMN type enum(
    'DEPOSIT',
    'TRANSFER',
    'PAYMENT',
    'EXCHANGE',
    'SAVING_DEPOSIT_SIGNUP',
    'SAVING_INSTALLMENT_SIGNUP',
    'SAVING_CANCEL_REFUND',
    'SAVING_MATURITY',
    'INSTALLMENT_PAYMENT'
    ) NOT NULL;
